#!/bin/bash


# Command Line Options

# What branch do we want to watch (default to origin/master)
branch="origin/master"

while getopts ":b:" opt; do
    case "$opt" in
    b)  branch="$OPTARG"
        ;;
    :)  echo "Required argument for option $OPTARG"
        exit 1
        ;;
    esac
done
shift $((OPTIND-1))

# Main watch function

function run {

latest_revision="none"

# loop forever, need to kill the process.
while [ 1 ]; do

    # get the latest revision SHA.
    current_revision=`git rev-parse $branch`

    # if we haven't seen that one yet, then we know there's new stuff.
    if [ $latest_revision != $current_revision ]; then
        # mark the newest revision as seen.
        latest_revision=$current_revision
        eval "$@"
    fi
    sleep 60
done
}

# Test git repository and start execution

if git rev-parse --git-dir > /dev/null 2>&1; then
	(run "$@")
else
	echo "Error: not a git repository"
fi
