#!/bin/bash

function run {

# what branch do we want to watch (default to origin/master)
if [ "$1" = "-b" ]; then
    branch="$2"
    shift 2
else
    branch="origin/master"
fi
latest_revision="none"

# loop forever, need to kill the process.
while [ 1 ]; do

    # get the latest revision SHA.
    current_revision=`git rev-parse $branch`

    # if we haven't seen that one yet, then we know there's new stuff.
    if [ $latest_revision != $current_revision ]; then
        # mark the newest revision as seen.
        latest_revision=$current_revision
        eval "$@"
    fi
    sleep 60
done
}

if git rev-parse --git-dir > /dev/null 2>&1; then
	(run "$@" &)
else
	echo "Error: not a git repository"
fi
